### ISSUE TITLE
Graphic visualization option not working

### ISSUE THREAD

**Issue by JamalEH** [ConesaLab/tappAS#10]
Hi,

I was trying to display graphic visualization summaries of different results obtained for modules 1 2 and 3 of tappAS but it seems not working or not yet supported. Please consider the attached screen shot to get the point of this issue (no graph type is shown in the dialogue window)
![Screenshot (54)](https://user-images.githubusercontent.com/52461533/85171693-c38af800-b26f-11ea-8674-e32aeb23e462.png)
 

Thank you so much for your help!
Best regards,
Jamal.

**Comment by aarzalluz** [comment]
Hi @JamalEH,

I take that you're trying to get the result summary graphics using the "Graphs" button in the upper bar of the application, right? This is an old option that we have not removed, but hasn't been updated in a bit -we're currently working on it. 

At the moment, the best and most intuitive option to display the graphic visualization summaries for any analysis is to open the results tab, and then go to the left hand-side bar in the upper panel (i.e. the green bar with all the different white icons), and click on the graphics icon (see screenshot below):

![Captura de pantalla de 2020-06-22 17-53-21](https://user-images.githubusercontent.com/19856199/85308591-a8a7c600-b4b1-11ea-803a-2d0accb55a20.png)

tappAS is very interactive and there are generally several paths to everything. If you get lost or struggle with the interpretation of a plot or parameter, you can always use the interactive help buttons ([?] icons) -they contain a lot of info and documentation on the different analyses!

Hope this helps,

Ángeles
