### ISSUE TITLE
SQANTI2 Input

### ISSUE THREAD

**Issue by hadjie01** [ConesaLab/tappAS#15]
Hello,

Is it possible to run tappAS using SQANTI2 output ("_classification.txt", "_junctions.txt", "_corrected.gtf")?
I created tappAS gff3 already using IsoAnnot1.5.py and I successfully run tappAS using only 2000 transcripts. However, when I click on "Show gene data visualization", I don't see any figures and below each transcript I get the following message: "No alignment data available...". Also, "structural_info.tsv" file is empty.
Could you please assist me?

Thanks a lot,
Evi

**Comment by psalguerog** [comment]
Hello Evi,

First of all, sorry for the delayed answer. IsoAnnot 1.5 is prepared to run only with the last version of SQANTI, it means it only works with SQANTI3. I have to recommend you to download and run again your analysis using the newest version of SQANTI.

Furthermore, we're preparing IsoAnnotLite 1.7 that will be released in the next days fixing some errors and upgrading the performance. It is possible you need this 1.7 version to run IsoAnnotLite without errors. I'll let you know when it's released.

Regards,
Pedro Salguero

**Comment by hadjie01** [comment]
Hello Pedro,

Thanks for the response! I fixed the column order of my classification file and it works fine. I might not be able to visualize the transcripts but I am still able to do differential analyses. Is there something else I should be aware of when using tappAS with SQANTI2?

Best,
Evi

**Comment by aarzalluz** [comment]
Hi @hadjie01,

I'm glad to hear you got IsoAnnotLite working with your SQANTI2 output! However, please consider switching to SQANTI3 -SQANTI2 is already deprecated and will no longer be maintained. In addition, SQANTI3 includes improvements in comparison to SQANTI2 and implements some new features, plots, etc. that will probably be of use when doing QC of your long-read transcriptome.

Keep in mind that the functional annotation, together with the feature-level analyses and the transcript and protein-level visualizations that are enabled by it, are one of tappAS' strongest features. Using SQANTI3+IsoAnnotLite you'll be able to run them and make the most of your data!

I'm closing this issue now, but if you do run SQANTI3 and have trouble with the annotation again, do not hesitate to contact us and we'll help you in any way we can.

Thank you for using tappAS! Best,


Ángeles
