### ISSUE TITLE
Jar file

### ISSUE THREAD

**Issue by rsalz** [ConesaLab/tappAS#2]
Just letting you know that in the latest release, the jar file version does not correspond to the source code version. The jar file is still at 1.0.01. Seems this was unintentional.

**Comment by aarzalluz** [comment]
Hi @rsalz,

Thank you for reporting this. We have now corrected the version number in the .jar file -feel free to download it again. Our numbering system is in fact three digit-based, so the correct version number is 1.0.1. 

I'm closing the issue now, but please contact us again if you run into any problems while using the application.

Ángeles
