### ISSUE TITLE
Data Matrix in View Expression Matrix in tappas is not normalized

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/tappAS#20]
Good afternoon, 
It seems that the data matrix available in TAPPAS by clicking in DATA -> View Expression Matrix is not normalized by TMM. 
I compared this with the RSEM data matix I used as input. But also with the RSEM data matrix that i normalized myself in R using the R code.
Is this expected to happen?
When I checked the avarage values available at DATA -> View Transcripts, I get values closer to the avarage of TMM normalized values I got in R.

**Comment by psalguerog** [comment]
Good morning Beatriz,

As you said, tappAS only allows to see the original matrix, but it has saved the normalized matrix in an external file. If you go to the folder tappasWorkspace, where tappAS saves all the project files, and you access your project [named as Project.XXXXXXXXXXX.tappas], you can find  two folders. The folder with the name **InputData** has the original and the normalized matrix (input_normalized_matrix.tsv). When tappAS requires the normalized matrix it will load that file, so it is fine.
 
To look for your project **ID** you can open your project and see the project properties. That's one of the ways to detect your Project.XXXXXXXXXXX.tappas folder.

In future versions of tappAS we will add the option to see the raw and normalized matrix.

Regards,
Pedro Salguero
