### ISSUE TITLE
syntax error near unexpected token newline

### ISSUE THREAD

**Issue by mei-du** [ConesaLab/tappAS#22]
Hi team,
I think this may not necessarily be a tappAS issue but I've been getting this error and haven't yet been able to find a solution:

<img width="793" alt="Screen Shot 2021-03-19 at 15 21 14" src="https://user-images.githubusercontent.com/58542302/111731034-bfefd480-88c6-11eb-8332-8a43aa04bf0a.png">

Could you offer any suggestions? Thank you!

**Comment by aarzalluz** [comment]
Hi @mei-du,

Thanks for reporting the error. Could you share some of your input data? It seems that it may related to file formatting, but we can only narrow it down further if we are able to replicate the error. 

Thanks,


Ángeles

**Comment by mei-du** [comment]
Hi Ángeles, invited you to my repository, thanks!

**Comment by aarzalluz** [comment]
Hi @mei-du,

Thanks! I had a look at your input data, and there are a couple of things you'll need to fix to get tappAS to run:

- First, your **expression matrix** does not contain headers for your columns, and therefore it is impossible for tappAS to match the _sample_ column in your design file to the expression values in the expression matrix. Please note that you don't need a header for the transcript ID column: just add the tab-separated sample names to your expression matrix, starting by the first sample name. An example below:

![Captura de pantalla de 2021-04-08 18-26-40](https://user-images.githubusercontent.com/19856199/114062622-01f1b200-9898-11eb-910b-59ca05f6dafb.png)

- Second, your **annotation GFF3** contains ENSEMBL transcript IDs (I suppose you've used tappAS ENSEMBL functional annotation for human), however, it appears by your expression matrix that you have quantified PacBio-generated transcript models. If so, you'll need to provide a functional annotation for your PacBio transcripts. Please use our [IsoAnnotLite](https://isoannot.tappas.org/isoannot-lite/) tool to obtain a tappAS-compatible file from your SQANTI3 output.

- Finally, do not forget to have a look at the Overview and FAQ sections in the [tappAS website](https://app.tappas.org/) for more info on how to load a project and how to work with long read-generated transcriptomes in tappAS. There's also some videotutorials [here](https://app.tappas.org/tutorials/) (I would recommend the ISMB2020 tutorial, as it is particularly comprehensive).

Fixing the expression matrix formatting and using the right functional annotation for your data should fix the issue you've been experiencing. If so, please let us know here and we'll close the issue.

Best,


Ángeles

**Comment by mei-du** [comment]
Hi @aarzalluz, I had a look at my original/full expression matrix and it has a header - I think it disappeared when I made the subset. I also realised I did use IsoAnnotLite and have a compatible gff3. I will update the data my repository, but I also tried to create a new project with these and am still getting the same error.

**Comment by aarzalluz** [comment]
Hi @mei-du,

I went ahead and used the updated files in your repository to try and reproduce the error, however, tappAS created the project correctly. This was the parameters I used: 

![Captura de pantalla de 2021-04-13 13-36-27](https://user-images.githubusercontent.com/19856199/114546493-7ee8a700-9c5d-11eb-8fdd-0edbcf95dfd1.png)

Seeing that your error seemed to be related to the normalization script, I checked whether it also worked when no normalization or filtering were performed, and I got no errors either.

I would suggest reviewing our [installation guide](https://app.tappas.org/resources/downloads/install.pdf) to see if there are any missing dependencies, including R packages, that you may have skipped installing. You should also check that you're using tappAS' most recent version, [v1.7.0](https://github.com/ConesaLab/tappAS/releases/tag/v1.0.7), which is the one I am using to create your project.

Let me know if any of this helps, or if you get a different error.

**Comment by mei-du** [comment]
Hi @aarzalluz,
I think it was a combination of Java/JRE installation issues (I don't have admin privileges) and Rscript, but the Mac Java workaround in the troubleshooting section worked for me. Thanks for your help!
