### ISSUE TITLE
is the Mean expression levels tmm normalized?

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/tappAS#24]
Good afternoon!
I would like to know if the Mean expression levels available in tappas (Data tab, View genes, View transcripts) is the avarage levels after tmm normalization.
Thank you 
Beatriz

**Comment by aarzalluz** [comment]
Hi @BeatrizdeToledo,

As my colleague @psalguerog indicated in issue #20, the data that is displayed in tappAS is not normalized, and this includes mean expression levels -however, please be aware that tappAS uses normalized data internally for all its analyses, as long as users have specified that they want to perform TMM normalization upon project creation.

We will include the option to view the normalized expression levels as well as the normalized expression matrix in future releases of tappAS. Until then, you'll need to follow his instructions to find the normalized expression matrix inside the project folder and perform any calculations that you may require outside of the application.

I'm closing the issue now, but feel free to contact us if you need help with any other aspects of tappAS.

Best,


Ángeles
