### ISSUE TITLE
differential polyadenilation analysis, 3 utr same coordinates

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/tappAS#25]
Good afternoon,
I performed the differential polyadenilation analysis in Tappas. 
I observed some of the cases that my q-value <0,05, the 3' UTR region has the same or almost the same coordinates.
I would like to know why this could be hapenning. Or is there another factor you consider for evaluating this?
Thank you 
Beatriz

**Comment by aarzalluz** [comment]
Hi @BeatrizdeToledo,

One of the parameters provided before UTRL analysis is the minimal difference (i.e. no. of basepairs) required to consider two UTRs to be different. If you open the **UTR Lengthening Analysis Parameters** window and click on **Help**, you'll see this:

> Minimum value for differentiation - number of base pairs to call a different UTR length between isoforms. All isoforms with UTR lengths differing less than x base pairs (where x is the provided threshold) are considered to have the same UTR length. Once UTR lengths for analysis have been selected, each length is weighted by the relative expression of the isoform (isoform expression / total gene expression), and sumed to provide a weighted 3' or 5' UTR length (wUTR).

As described above, in this analysis UTR lengths are weighted by isoform expression, and a statistical test is performed to see if UTR usage is significantly changing between conditions/across time points. Therefore, you'll obtain small q-values whenever the global change in UTR length for that gene is significant, i.e. if the gene shows significantly favored expression of alternative isoforms with a longer or shorter UTR. While this does not depend specifically on UTR coordinates, you can control the minimum length difference considered using the **Minimum value for differentiation** parameter. If you increase this threshold, you'll see that the criteria becomes more stringent and therefore that less genes are considered for the analysis, excluding those that don't have sufficiently distinct 3'/5' UTRs among their isoforms.

If you want to dig deeper into how UTR lengthening analysis is performed, please consider reading the Methods section in [the tappAS paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02028-w). Also, always remember to read the built-in **Help** menus in the application: they contain all of the required information to understand the parameters provided to the different analyses and output result tables, as well as to interpret plots.

Best,


Ángeles

**Comment by aarzalluz** [comment]
It appears that the question is solved, so I'm going to close the issue now. Please, feel free to reopen if you need to follow up on this.
