### ISSUE TITLE
problem viewing protein alignments in tappAS with gff3 created via isoAnnotLite

### ISSUE THREAD

**Issue by kmattioli** [ConesaLab/tappAS#31]
Hello -

Thanks for all your work on tappAS! I am loving the tool as an easy way to visualize isoforms.

I am having one issue that I can't figure out. I have PacBio data that I analyzed via SQANTI3 and created the required gff3 file using the `--isoAnnotLite` flag. I am noticing that in many cases, when I try to load the protein alignment view, I am getting the error:

```
[ERROR] Gene protein annotations must have 'protein' as first entry. Entry: ~nt_flushdata
```

I have gotten the above error in 4/7 genes that I've tried to load so far.

The only potential pattern I can see with these 4/7 in the gff3 file is that the first isoform listed in the transcripts view also has a predicted NMD feature in the gff3.

Would love to know any solutions or workarounds for the time being if this ends up being a bug fix! Thanks!

-kaia

**Comment by kmattioli** [comment]
Following up: this issue went away when I filtered out all "NMD" features in the gff3. For what it's worth, it also looks like the gff3 includes predicted NMD features that are _not_ predicted by SQANTI3.

Leaving open as it still seems like a potential bug, but there is a workaround!

**Comment by psalguerog** [comment]
Hello @kmattioli,

I am sorry for the problem you have been having with tappAS and also for the delay in the answer.

It seems to be a bug on IsoAnnotLite. As your annotation comes from SQANTI3, it would be really helpful if you could run the newest version of IsoAnnotLite (2.7) manually and let me know if the error persists.

You can find the link of download on the next webpage: [IsoAnnotLite](https://isoannot.tappas.org/isoannot-lite/)

To run IsoAnnotLite, you have to use the following SQANTI3 output files:
- my_corrected.gtf
- my_classification.txt
- my_junctions.txt 

Furthermore, you have to download the same GFF3 annotated file you used in SQANTI3 with the argument `-ggf3 annotation.gff3`. The argument `-novel` is highly recommended.

After running IsoAnnotLite, try to create a new project on tappAS with the same input you did. If the problem persists, I would have to ask you to share your SQANTI3 files used in IsoAnnot to debug the tool.

Thank you for contacting us.

Regards,
Pedro Salguero

**Comment by aarzalluz** [comment]
Closing unless OP reopens or users report similar issues.
