### ISSUE TITLE
[ERROR] java.lang.StringIndexOutOfBoundsException Code Exception: String index out of range: -1

### ISSUE THREAD

**Issue by gouwei1** [ConesaLab/tappAS#36]
I prepared three input files for "other species" and "Single Series Time-Course" like these:

experimental_design.tsv:
sample	time	group
C_b5_1	1	CASE
C_b5_2	1	CASE
C_b5_3	1	CASE
C_b2_1	3	CASE
C_b2_2	3	CASE
C_b2_3	3	CASE
.......

expression_matrix.tsv:
C_b5_1	C_b5_2	C_b5_3	C_b2_1	C_b2_2	C_b2_3
GENE:SOLYC06G005000.3_1	179.865	224.445	206.858	247.963	145.243	370.191
GENE:SOLYC06G005060.3_1	24987.309	25008.774	25754.024	23837.332	23696.704	26465.503
GENE:SOLYC06G005060.3_2	91.2	109.771	64.387	115.48	98.362	117.255
......

IsoAnnotLite.gff3:
SeqName	Source	Feature	Start	End	Score	Strand	Phase	Attributes
GENE:SOLYC00G500218.1_1	tappAS	transcript	1	1975	.	+	.	ID=mRNA:Solyc00g500218.1.1; primary_class=full-splice_match; PosType=T
GENE:SOLYC00G500218.1_1	tappAS	gene	1	1975	.	+	.	ID=gene:Solyc00g500218.1; Name=gene:Solyc00g500218.1; Desc=gene:Solyc00g500218.1; PosType=T
GENE:SOLYC00G500218.1_1	tappAS	CDS	107	1840	.	+	.	ID=Protein_GENE:SOLYC00G500218.1_1; Name=Protein_GENE:SOLYC00G500218.1_1; Desc=Protein_GENE:SOLYC00G500218.1_1; PosType=T
GENE:SOLYC00G500218.1_1	tappAS	CDS	3929049	3929344	.	+	.	Chr=SL4.0ch00; PosType=T
GENE:SOLYC00G500218.1_1	tappAS	CDS	3929440	3929541	.	+	.	Chr=SL4.0ch00; PosType=T
GENE:SOLYC00G500218.1_1	tappAS	CDS	3929651	3930444	.	+	.	Chr=SL4.0ch00; PosType=T
GENE:SOLYC00G500218.1_1	tappAS	CDS	3931032	3931573	.	+	.	Chr=SL4.0ch00; PosType=T
GENE:SOLYC00G500218.1_1	tappAS	genomic	1	1	.	+	.	Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	exon	3928943	3929344	.	+	.	Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	exon	3929440	3929541	.	+	.	Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	exon	3929651	3930444	.	+	.	Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	exon	3931032	3931708	.	+	.	Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	splice_junction	3929345	3929439	.	+	.	ID=junction_1_canonical; Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	splice_junction	3929542	3929650	.	+	.	ID=junction_2_canonical; Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	splice_junction	3930445	3931031	.	+	.	ID=junction_3_canonical; Chr=SL4.0ch00; PosType=G
GENE:SOLYC00G500218.1_1	tappAS	protein	1	578	.	+	.	ID=Protein_GENE:SOLYC00G500218.1_1; Name=Protein_GENE:SOLYC00G500218.1_1; Desc=Protein_GENE:SOLYC00G500218.1_1; PosType=P
GENE:SOLYC00G500218.1_1	TranscriptAttributes	3UTR_Length	1841	1975	.	+	.	ID=3UTR_Length; Name=3UTR_Length; Desc=3UTR_Length; PosType=T
GENE:SOLYC00G500218.1_1	TranscriptAttributes	5UTR_Length	1	107	.	+	.	ID=5UTR_Length; Name=5UTR_Length; Desc=5UTR_Length; PosType=T
GENE:SOLYC00G500218.1_1	TranscriptAttributes	CDS	107	1840	.	+	.	ID=CDS; Name=CDS; Desc=CDS; PosType=T
GENE:SOLYC00G500218.1_1	TranscriptAttributes	polyA_Site	1975	1975	.	+	.	ID=polyA_Site; Name=polyA_Site; Desc=polyA_Site; PosType=T
......

After I clicked "OK", an error occurred like this:
15:38 - Checking specified annotation file: C:\Users\gouwei\Desktop\其他\20211011\all\IsoAnnotLite.gff3
15:38 - Checking design file: C:\Users\gouwei\Desktop\其他\20211011\all\experiment_design.tsv
15:38 - Design file passed initial check.
15:38 - Checking specified matrix file (Time_Course_Single): C:\Users\gouwei\Desktop\其他\20211011\all\expression_matrix.tsv
15:38 - Matrix file passed initial check.
15:38 - The custom annotation file has been modified. We are going to load the version you used to create the project.
15:38 - Annotation loaded correctly. Check if the project contains the correct annotation or you want to create a new one.
15:38 - Input Data dialog results: tappas.DlgInputData$Params@54fcf3c
15:38 - The custom annotation file has been modified. We are going to load the version you used to create the project.
15:38 - Annotation loaded correctly. Check if the project contains the correct annotation or you want to create a new one.
15:38 - Process Input Data script is running...
15:38 - [ERROR] java.lang.StringIndexOutOfBoundsException Code Exception: String index out of range: -1
15:38 - Remove file exception (C:\Users\gouwei\tappasWorkspace\References\UserDefined.72202423_4.tappas\annotations.db): C:\Users\gouwei\tappasWorkspace\References\UserDefined.72202423_4.tappas\annotations.db: 另一个程序正在使用此文件，进程无法访问。
15:38 - Closing project 'test'

Is there any problems with my input files?
Thank you!

**Comment by aarzalluz** [comment]
Hi @gouwei1,

I can't see anything wrong with the formatting you show, other than your missing time 0 in your design file. Could you re-number your time points to start with time 0, and make them sequential (that is, 0, 1, 2, etc.) and see if the error persists?

You might also want to check that all the samples included in you expression matrix are also present in the design file, and that they are in the same order.

If none of the suggestions above fix the error, would you be willing to share your data for debugging? You can send them via email to angeles.arzalluz [at] gmail.com.

Best,

Ángeles

**Comment by gouwei1** [comment]
I have renumbered to start with time 0 and make them sequential (that is, 0, 1, 2, etc.) in the design file as you recommended, and also checked the second potential error you mentioned, while it still can not procceed. 

Does the transcript name must be formatted as "PB.<loci_index>.<isoform_index>"?

**Comment by aarzalluz** [comment]
It is not required that the transcript IDs are formatted as PacBio IDs, however, I just realized that there is something else that might be causing the issue. 

There are some characters in your IDs that tappAS may not be detecting as valid, i.e. the colon (the : symbol). Could you try and replace it with a dot in your IDs, and try again? You'll need to do that on the first columns of both the expression matrix and the GFF3 it to work.

**Comment by gouwei1** [comment]
Still not work after removing the colon....

I have sent the three input files to your e-mail. I would appreciate it very much if you could find out what the problem is as soon as possible.

Thanks for your help!

**Comment by aarzalluz** [comment]
I'm sorry to hear that -I just received your files, I'll have a look at it and try to get back to you with a solution t as soon as possible.

**Comment by gouwei1** [comment]
OK...
Thanks for your help!

**Comment by psalguerog** [comment]
Hi @gouwei1,

I've been able to fix your problem. There are two things to consider.

The first one, the GFF3 file does not require a header. It is only an annotation file. IsoAnnotLite does not generate the header, so I guess you added it afterwards? If not, tell me what you did to study the cause.

Then, the second error consists of the use of ":" in the attribute fields for some annotations such as "ID=Protein:Solyc01g005000.3.1". 

I've replaced all the ":" by "_" and the project was created correctly.

Best,
Pedro Salguero

**Comment by gouwei1** [comment]
The problems have been solved after correct the two things you mentioned. Thank you!

The header in GFF3 file was added by me, because I refered to the annotation file sample at https://app.tappas.org/ufaqs/projects/

May I ask another question? Which version of R is recommended? There are errors that show some specific packages are only for a specific version of R. Or how to install them in a same version of R?

Best,
Wei Gou

**Comment by psalguerog** [comment]
I'm glad you can create your project!

Also, I'm sorry that the webpage can not be clear enough. I've updated the text to indicate the header should not be added to the annotation file. 

Related to the R version and package problems, would you ask the question in another issue? It would help other people to identify the same question/problems. Thank you!

Best regards,
Pedro Salguero
