### ISSUE TITLE
IsoAnnotLite error in createGTFFromSqanti: "ValueError: too many values to unpack (expected 4)"

### ISSUE THREAD

**Issue by KellyDREN** [ConesaLab/tappAS#39]
Hi, I have run following code to produce a gff3 file for TappAS

python IsoAnnotLite_v2.7.0_SQ3.py hq.5merge.collapsed_corrected.gtf hq.5merge.collapsed_classification.txt hq.5merge.collapsed_junctions.txt

Got error:
Running IsoAnnot Lite 2.7.0...

Reading SQANTI 3 Files and creating an auxiliar GFF...
Traceback (most recent call last):
  File "IsoAnnotLite_v2.7.0_SQ3.py", line 3115, in <module>
    main()
  File "IsoAnnotLite_v2.7.0_SQ3.py", line 2958, in main
    run(args)
  File "IsoAnnotLite_v2.7.0_SQ3.py", line 3093, in run
    dc_SQexons, dc_SQcoding, dc_SQtransGene, dc_SQstrand = createGTFFromSqanti(gtf, classification, junctions, dc_gene_description, filename) 
ValueError: too many values to unpack (expected 4)

Any one can help?

**Comment by aarzalluz** [comment]
Hi @KellyDREN,

Just from your command line input, there are a couple of things to check first:

- Are you running IsoAnnotLite with python3? 
- You have not provided some of the inputs to generate a GFF3, in particular, there is no pre-annotated GFF3 files to transfer features from. You must provide this via the `-gff3` argument. Please check the [IsoAnnotLite website](https://isoannot.tappas.org/isoannot-lite/) for instructions.

Could you check these two things and let us know if the error persists?

Best,


Ángeles

**Comment by lananh-ngn** [comment]
Hi,
I am encountering the same problem but I am curious about the -gff3 argument since it is written in the manual that this argument is optional. (I am running it with python3).
Thank you for developing the tools.
Best regards,
Lan Anh

**Comment by aarzalluz** [comment]
Hi @lananh-ngn,

It is optional, but it is required if you want your desired output to include functional features. Otherwise, you can just run it without it and it will be converted to a tappAS-compatible GFF3 with only structural information in it.

Could you (and/or @KellyDREN) share your SQANTI3 output files for @psalguerog to debug the tool?

Best,

Ángeles

**Comment by lananh-ngn** [comment]
Hi!
Thank you for the quick answer. In the end, by providing the gff3 file the error is not displayed anymore. 
I will send you the log when the error appears tomorrow.
Best regards,
Lan Anh

**Comment by aarzalluz** [comment]
Hi @lananh-ngn and @KellyDREN,

We just released a new version of IsoAnnotLite (available at the [website](https://isoannot.tappas.org/isoannot-lite/)) in which we fixed the --gff3 issue. This means that you should now be able to run IsoAnnotLite successfully without providing a GFF3. Please, give it a go and let us know if that works.

Best,

Ángeles

**Comment by lananh-ngn** [comment]
Hi!
Thank you for your fast response and updating. I just tried it and it worked.
Thank you.
Best regards,
Lan Anh

**Comment by aarzalluz** [comment]
Glad to hear that! Closing the issue now. Do not hesitate to contact us if you have any more questions/problems.
