### ISSUE TITLE
Differential Isoform Usage Analysis Failed

### ISSUE THREAD

**Issue by yunzhang77** [ConesaLab/tappAS#41]
Greetings- 

I recently read your published paper about tappAS and decided to give it a try. I study isoform switching events in cancer and I have previously been using other isoform switching algorithms/packages. 

I used a dataset that we have in the lab to run differential isoform usage analysis. After 50-minutes of running, it returned with an error message. I couldn't figure out what is the reason leading to this error, so I decided to post it on GitHub. 

The error message is as follows:
```
13:11:01.697 Warning message:
13:11:01.698 In DESeqDataSet(rse, design, ignoreRank = TRUE) :
13:11:01.698   some variables in design formula are characters, converting to factors
13:11:01.735 Error in `[.data.frame`(norm.counts, , rownames(factors[[1]])) : 
13:11:01.735   undefined columns selected
13:11:01.735 Calls: podiumChange -> data.frame -> apply -> [ -> [.data.frame
13:11:01.735 Execution halted
13:11:01.735 Transcripts Differential Isoform Usage Analysis script ended. Exit value: 1
```
It looks to me that there is a data frame-related issue when running DEXSeq. I am just wondering if you could provide me with some suggestions on resolving this issue. Thank you in advance :) 

The expression matrix contains 2 experimental groups with a total of 44 samples. I was able to successfully run differential expression analysis and functional diversity analysis. It looks like a really powerful software, so I hope it can get fixed so that I can generate some data for publication :) 

Thank you for your help!

**Comment by psalguerog** [comment]
Hello @yunzhang77,

I am sorry the answer has taken so long. I was checking the code and I am not able to reproduce the error. The function where the code fails uses the experiment design and the matrix data file. It seems that a sample name (in the experiment design) cannot be found as a column in the gene expression file data. Try to check all the samples are in both files again.

As a suggestion try to avoid special characters like `$%*¨^"?...` in sample names. Alphanumerical characters and underscores are allowed.

Also, I recommend running it again with a subgroup of data to not wait more than 50min. You can select just 4-10 samples and use them to create a new project. 

Regards,
Pedro Salguero

**Comment by christine-liu** [comment]
Sorry to post to a closed issue, but I'm also running into an issue with the DIU analysis failing as well
I only have samples labeled with numbers, and the samples from the design file match the counts matrix samples. I get the following error:

``12:34:14.608 EMC2:10127_108443636_108486917                   0:0:6:...
12:34:14.608 RNF10:1013_120534355_120576882                 32:0:28:...
12:34:14.631 Error in `[.data.frame\`(norm.counts, , rownames(factors[[1]])) : 
12:34:14.634   undefined columns selected
12:34:14.634 Calls: podiumChange -> data.frame -> apply -> [ -> [.data.frame
12:34:14.635 Execution halted
12:34:14.635 Transcripts Differential Isoform Usage Analysis script ended. Exit value: 1``

It seems like it's generally working b/c it prints out "DataFrame with 6 rows and 9 columns" and some of the information, but I'm wondering if it's "failing" b/c everything's getting filtered out for non-significance?

Thanks in advance!
Christine

**Comment by aarzalluz** [comment]
Hi @christine-liu -could you try renaming your samples with letters+numbers instead? I am not sure, but it may be problematic for R. If not, we might need to ask you to send your data so that we can look into it.

**Comment by christine-liu** [comment]
Hi @aarzalluz!
That worked! It looks like it needs to start with a letter.. I originally tried renaming my samples 1_C, 2_C, 3_C, etc before posting here and it still failed, but trying C1, C2, C3 works! Glad it was an easy fix :)
Thank you!

**Comment by aarzalluz** [comment]
No worries @christine-liu! Glad that worked :)
