### ISSUE TITLE
Differential polyadenylation results are empty

### ISSUE THREAD

**Issue by joelnitta** [ConesaLab/tappAS#50]
I included polyadenylation annotations in my GFF file by using the [SQANTI3 options](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-Quality-Control#polya-motif-data---polya_motif_list) `--polyA_motif_list` and `--polyA_peak`. I can see that the polyA annotations are included in the GFF file imported to tappAS in the transcripts list:

<img width="1323" alt="polyA" src="https://user-images.githubusercontent.com/13459362/231350815-f70ce135-8265-4cc8-9552-28ce8f4a735e.png">

However, when I run the differential analysis under "Features" -> "Run Analysis", although the analysis seems to run, the final output is empty: just a blank table that says "No content in table".

This is a custom GFF3 file so the reason may have something to do with how it is formatted. If needed I can send it by email. Please let me know.

Thank you very much!

**Comment by almart7** [comment]
Dear Joel,

Thank you for using tappAS. We are releasing a new version of the tool soon, in which this problem is solved. Sorry for the inconveniences!

**Comment by almart7** [comment]
Hello @joelnitta, we have released tappAS 1.0.8 where we solved this bug. Contact us if you need anything else!

**Comment by joelnitta** [comment]
Thanks @almart7! I can confirm this works now :)
