### ISSUE TITLE
unable to create a project 

### ISSUE THREAD

**Issue by JingAnyaSun** [ConesaLab/tappAS#54]
Hi, I tried to create a new project but encounter a problem, please see the error message below: 

6:23 - Matrix script: /var/folders/mm/2sw47w_n6pl2b3rsphnshx1c0000gn/T/tappas6007173753775674484.R
16:23 - Rscript: /Users/jingsun/Desktop/PhD project/epitope prediction/methodology/tappas/tappas.R
16:23 - Running ExpMatrix filter/normalization script:
    [/Users/jingsun/Desktop/PhD project/epitope prediction/methodology/tappas/tappas.R, /var/folders/mm/2sw47w_n6pl2b3rsphnshx1c0000gn/T/tappas6007173753775674484.R, /Users/jingsun/tappasWorkspace/Projects/Project.659628375.tappas/InputData/input_matrix.tsv, /Users/jingsun/tappasWorkspace/Projects/Project.659628375.tappas/InputData/exp_factors.txt, /Users/jingsun/tappasWorkspace/References/Mus_musculus/Ensembl/86/transcript_lengths.tsv, /Users/jingsun/tappasWorkspace/Projects/Project.659628375.tappas/InputData/input_normalized_matrix.tsv, 1.0, 100.0, Y]
16:23 - Input matrix Filter/Normalization process started, process id: java.lang.UNIXProcess@2e620dc4
16:23 - Input matrix Filter/Normalization process is running...
16:23 - Input matrix Filter/Normalization script ended. Exit value: 0
16:23 - Creating expression matrix file.
16:23 - [ERROR] Unable to write project data results to file.
16:24 - Closing project 'd1'

Many thanks
Jing

**Comment by JingAnyaSun** [comment]
I have resolved this issue. Just in case someone else might encounter the same problem, I'd like to share my experience here. My system is MacOS Monterey version 12.6, M1 chip. After following the instructions for installation, a window popped up asking to choose the path for 'Rscript.exe', for MacOS, the path is in '/usr/local/bin/Rscript'. Don't copy paste the path directly, but rather click on the ... and select it manually. Then it will work.

**Comment by almart7** [comment]
Thank you for sharing your solution!
