### ISSUE TITLE
cannot run Tappas with human transcripts 

### ISSUE THREAD

**Issue by JingAnyaSun** [ConesaLab/tappAS#55]
Hi tappAS team,

Many thanks for developing a nice tool for differential alternative splicing analysis, which I find could be quite useful for my project. However, when I was trying to use the software, I encountered a problem of not being able to create a project with the error message of reading 0 transcripts. I have tested the example data and everything worked well, but when it comes to my own data(please see below, human transcripts, here I converted to txt files since github does not support uploading tsv files), it did not work. For the annotation file, I selected the embedded human Ensembl 86 reference. I wonder if you could kindly let me know how to fix this issue. Thanks.

[experimental_design2.txt](https://github.com/ConesaLab/tappAS/files/12807229/experimental_design2.txt)

[merged_kallisto_transcript_raw_counts copy.txt](https://github.com/ConesaLab/tappAS/files/12807233/merged_kallisto_transcript_raw_counts.copy.txt)

Best,
Jing

**Comment by almart7** [comment]
Dear @JingAnyaSun thank you for using tappAS! I've found the cause of your problem. The name of the transcripts in the count matrix and the annotation file has to be the same.You used our Ensembl 86 annotation file, in which transcripts have no version in their name (ENST00000434970). However, your count matrix does include the version (ENST00000434970.2) therefore the names doesn't match and tappAS detects 0 transcripts. You can just remove the version of the transcripts in your matrix file and tappAS will be able to create the project. 

Best,
Alessandra

**Comment by JingAnyaSun** [comment]
Hi Alessandra, 

Thanks for your prompt reply. I've tried what you suggested, and it worked!!! :D 

Best,
Jing
