### ISSUE TITLE
Can tappAS perform differential analysis on single-cell full-length RNA-seq?

### ISSUE THREAD

**Issue by springwellflow** [ConesaLab/tappAS#56]
Can tappAS perform differential analysis on single-cell full-length RNA-seq?

**Comment by aarzalluz** [comment]
Hi @springwellflow,

Currently, tappAS only supports bulk RNA-seq experimental designs and methods. If you are interested in performing differential expression in full-length scRNA-seq, I suggest you check the [acorde](https://github.com/ConesaLab/acorde) R package, which contains some useful wrapper functions for this.

Best,

Ángeles
