### ISSUE TITLE
Error while launching tappAS

### ISSUE THREAD

**Issue by cbenoitp** [ConesaLab/tappAS#6]
Hi,

I would like to use tappAS on my data but I have been unable to launch the program using the precompiled version (tappas.jar).

I tried launching tappAS (v1.0.1) with this command:
```
java -jar tappAS.jar
```
And I got the following error:
```
Error: Could not find or load main class tappas.Tappas
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

I am trying to use tappAS on a macOS Mojave (10.14.6), and I am using the last oracle jdk version installed with homebrew:
```
> java --version
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```
I also installed the R dependencies using the command given in the installation instruction:
```
source("http://app.tappAS.org/resources/downloads/tappAS_packages.R")
```

Thank you for your help,
Clara

**Comment by psalguerog** [comment]
Dear Clara,

tappAS was developed in Java 8 and if you have more than 4Gb of RAM (tappas requires 8Gb) we recommend to download a 64bit version of Java. 

I have seen you have a 64 bits version. However, your Java version is the 14.0. It is a new version and tappAS has no be tested on it. Try to install Java 8 which you can find [here](https://www.java.com/en/download/manual.jsp).

We tested tappAS in Windows, Linux and Mac computers with Java 8 and it works correctly. I attached the Java version in one of our computers.

![javaVersionLinux](https://user-images.githubusercontent.com/59012739/84672807-42f39100-af29-11ea-939a-0252907b06d2.jpg)

Regards,
Pedro Salguero

**Comment by cbenoitp** [comment]
Dear Pedro,

Thank you for your answer.

I managed to install Java 8 from your link. Then, I installed "jenv" to be able to use this version of java. And now, I can launch tappAS without any issue.

Thank you again,
Clara
