### ISSUE TITLE
R packages not loaded/available in tappas

### ISSUE THREAD

**Issue by BeatrizToledo** [ConesaLab/tappAS#8]
Good evening!

At the moment I am having problems regarding the R packages available for me. Basically the only tool available for me is the masigpro in tappas GUI. When I try to run differential isoform usage I don't have the DEXSeq or edgeR options for example, only masigpro.

On R studio, I installed all packages (source("http://app.tappAS.org/resources/downloads/tappAS_packages.R")) and "loaded one by one using library()
The packages seem to be installed in the folder: /Users/beatriztoledo/Library/R/3.6/library

I successfully downloaded tappas, although I can only open it by running java -jar tappas.jar on the terminal.

I also checked that I am using the correct version of java and R
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

These are the technical infrmations in the initial tappas page:
Technical information
tappas version: 1.0.1
User: beatriztoledo
ProcessID: 1663
JavaFX: ver 8.0.181-b12
OS: Mac OS X ver 10.13.6
Architecture: x86_64
Available processors, cores, for JVM: 4
Available memory, for JVM: 1.78 GB
R scripting front-end version 3.6.1 (2019-07-05)

which java = /usr/bin/java
which Rscript = /usr/local/bin/Rscript
Java Environment (System.getenv()):
    PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/TeX/texbin
    JAVA_ARCH: x86_64
    SHELL: /bin/bash
    TERM_PROGRAM: Apple_Terminal
    SECURITYSESSIONID: 186a7
    OLDPWD: /Users/beatriztoledo
    TERM: xterm-256color
    USER: beatriztoledo
    TMPDIR: /var/folders/gt/k9rys2y1561_5hc7g2jhpcm00000gp/T/
    SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.TeocrO4IgM/Listeners
    XPC_FLAGS: 0x0
    TERM_SESSION_ID: B08709A8-A827-41FD-9488-8A117CE6509E
    __CF_USER_TEXT_ENCODING: 0x1F6:0x0:0x0
    Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.LuTa2OcnLS/Render
    com.apple.java.jvmTask: CommandLine
    LOGNAME: beatriztoledo
    JAVA_MAIN_CLASS_1663: tappas.Tappas
    LC_CTYPE: UTF-8
    XPC_SERVICE_NAME: 0
    PWD: /Users/beatriztoledo/Downloads
    TERM_PROGRAM_VERSION: 404.1
    HOME: /Users/beatriztoledo
    SHLVL: 1
    _: /usr/bin/java
java.io.tmpdir:
/var/folders/gt/k9rys2y1561_5hc7g2jhpcm00000gp/T/
Script Environment (printenv):
    TERM_PROGRAM=Apple_Terminal
    SHELL=/bin/bash
    TERM=xterm-256color
    TMPDIR=/var/folders/gt/k9rys2y1561_5hc7g2jhpcm00000gp/T/
    Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.LuTa2OcnLS/Render
    TERM_PROGRAM_VERSION=404.1
    OLDPWD=/Users/beatriztoledo
    TERM_SESSION_ID=B08709A8-A827-41FD-9488-8A117CE6509E
    USER=beatriztoledo
    SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.TeocrO4IgM/Listeners
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/TeX/texbin
    PWD=/Users/beatriztoledo/Downloads
    XPC_FLAGS=0x0
    XPC_SERVICE_NAME=0
    SHLVL=1
    HOME=/Users/beatriztoledo
    LOGNAME=beatriztoledo
    LC_CTYPE=UTF-8
    SECURITYSESSIONID=186a7
    _=/usr/bin/java
    __CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
    com.apple.java.jvmTask=CommandLine
    JAVA_ARCH=x86_64
    JAVA_MAIN_CLASS_1663=tappas.Tappas

**Comment by psalguerog** [comment]
Dear Beatriz,

Thank you too for sharing your problem.

If you run tappAS for time-Course experiments, for Differential Isoform Usage (DIU) and Differential Expression (DE) analyses, you can run just maSigPro method. I recommend you click on the "Help" buttons each time you have some doubt in tappAS.

DEXSeq or edgeR are not implemented in tappAS for Time-Course experiments. Instead of that, we use maSigPro, and DEXSeq for two-group comparison and edgeR for DE also for two groups.

I hope I have could help you.

Regards,
Pedro Salguero

**Comment by aarzalluz** [comment]
Hi @BeatrizToledo 

Thank you for giving tappAS a go! I'm closing the issue now, but feel free to contact us if you run into a bug or have any more questions.

For general questions on the methods that tappAS relies on or how the analysis are performed exactly, I recommend reading the Methods section in our recently published [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02028-w#Sec11). It contains a thorough description of all methods and metrics and how they are calculated. I think you may also find the manuscript useful to see what kinds of analyses can be run and how to combine them to make the most of your data -tappAS is very flexible, so feel free to mix it up!

Cheers,

Ángeles
